### ISSUE TITLE
Please remove upload_map.yml from .gitignore

### ISSUE THREAD

**Issue by ballaneypranav** [UNSW-iGEM/wiki-2020#11]
Hi,
I noticed you're using WikiSync for uploading your wiki and I would like to offer a suggestion: Could you please remove `upload_map.yml` from `.gitignore`?

The upload map keeps track of files uploaded on each run of WikiSync. If it is added to `.gitignore`, the log is ignored each time and every single file is uploaded each time you run it. This can be verified on the [iGEM Upload Log](https://2020.igem.org/wiki/index.php?title=Special:Log/upload&offset=&limit=500&type=upload&user=) where all uploads by teams can be seen.

Regards,
Pranav

**Comment by JackRobbers** [comment]
Hi Pranav, yep will do. Appreciate the WikiSync software heaps as well, has been really useful.

**Comment by ballaneypranav** [comment]
Thanks! Glad you found it helpful!
